image: ubuntu

variables:
  SOME_VAR: "some value"

stages:
  - build
  - test
  - sonarqube
  - deploy


before_script:
  - echo "Start CI/CD"
  - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  - echo $CI_JOB_STAGE  # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

build:
  image: maven:latest

  stage: build
  script:
    - echo "Build process"
    - mvn clean package -Dmaven.test.skip=true
    - echo "Build ok"
  only:
    - master
  tags:
    - alpine-docker

unittest:
  image: maven:latest
  
  stage: test
  script:
    - echo "start test"
    - echo "test ok"
  only:
    - master
  tags:
    - alpine-docker

katalon_test_suite:
  stage: test
  script:
    - echo "start katalon test suite"
    - echo "katalon test suite ok"
  only:
    - master
  tags:
    - alpine-docker
    

sonarqube:
  image: maven:latest
  stage: sonarqube
  script:
    - echo "start sonarqube"
    - echo "sonarqube ok"
    #- mvn clean package sonar:sonar -Dsonar.projectKey=hotel -Dsonar.host.url=http://157.26.83.83:9000 -Dsonar.login=4e9efa18f023c7809b1e6944f97435a1b23a3613 -Dmaven.test.skip=true
  only:
    - master
  tags:
    - shell-hotel-test


deploy_ssh:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy apps"
    - docker-compose down
    - docker-compose up -d
    - echo "deploy ok"
  only:
    - master
  tags:
    - shell-hotel-test
  when: manual

after_script:
  - echo "End CI/CD"
